config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  devise_for :users
  resources :custom_users, :teams, :matchs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/constant.rb
module Constant
	WINS_GAME_CONDITION = 2
	MAX_GAME_PER_MATCH = 3
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :match
  belongs_to :winner, class_name: "Team"
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :team_a, class_name: "Team"
  belongs_to :team_b, class_name: "Team"
  has_many :games
end

app/models/match_service.rb
class MatchService
	def create_invalid?(func_params = {})
		params = func_params[:params]
		err = []
		if !params[:match][:team_a_id].present?
			err.push "First team is missing"
		end
		if !params[:match][:team_b_id].present?
			err.push "Second team is missing"
		end
		if params[:match][:team_a_id] == params[:match][:team_b_id]
			err.push "First team and second team must be different"
		end

		relevant_games = params[:game].select{|game| game[:winner].present? && game[:score].present?}
		if relevant_games.count < 2
			err.push "Please input enough games info"
		end

		if relevant_games.select{ |game| !game[:winner].in?([params[:match][:team_a_id], params[:match][:team_b_id]]) }.any?
			err.push "Wrong team is input in game info"
		end

		if relevant_games.select{ |game| !game[:score].to_i.in?((0..10)) }.any?
			err.push "Incorrect score number"
		end

		most_wins = max_count(relevant_games.map{|game| game[:winner]})
		if most_wins < 2
			err.push "Game info is not enough to decide winner"
		end
		
		if err.any?
			return err
		end
		return false
	end

	def update_invalid?(*params)
		create_invalid?(*params)
	end

	private

	def max_count(arr)
		arr.uniq.map { |n| Rails.logger.info arr.count(n) ; arr.count(n) }.max
	end
end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/team_player.rb
class TeamPlayer < ApplicationRecord
  belongs_to :team
  belongs_to :player
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/custom_users_controller.rb
class CustomUsersController < ApplicationController
	def index
		@users = User.all
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.email = params[:user][:email]
		@user.first_name = params[:user][:first_name]
		@user.last_name = params[:user][:last_name]
		@user.save
		redirect_to action: "edit", id: params[:id]
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
include Constant
	def index
		teams = Team.all
		matchs = Match.all
		games = Game.all
		matchs_count = matchs.count
		@teams = []
		teams.each do |team|
			current_team = {}
			current_team["id"] = team.id
			current_team["name"] = team.name
			relevant_matchs = matchs.select{|m| m.team_a_id == team.id || m.team_b_id == team.id}
			current_team["match_play"] = relevant_matchs.count
			wins = 0
			relevant_matchs.each do |match|
				if games.select{|game| game.match_id == match.id && winner_id = team.id}.count >= WINS_GAME_CONDITION
					wins += 1
				end
			end
			current_team["win_ratio"] = ( wins / relevant_matchs.count.to_f * 100 ).round(2)
			@teams.push	current_team
		end
		@teams = @teams.sort_by{|team| team["win_ratio"]}.reverse
	end
end

app/controllers/matchs_controller.rb
class MatchsController < ApplicationController
include Constant
	def index
		@matchs = Match.all
	end

	def new
		@match = Match.new
		@list_teams = Team.all.collect{|item| [item.name, item.id]}
	end

	def create
		create_is_invalid = MatchService.new.create_invalid?(params: params)
		if create_is_invalid
			flash[:err] = create_is_invalid
			redirect_to action: "new"
			return
		end
		@match = Match.new
		@match.team_a_id = params[:match][:team_a_id]
		@match.team_b_id = params[:match][:team_b_id]
		@match.save
		if params[:game].any?
			params[:game].each do |game|
				if !game[:winner].present? || !game[:score].present?
					next
				end
				current_game = Game.new
				current_game.match_id = @match.id
				current_game.winner_id = game[:winner]
				current_game.score = game[:score]
				current_game.save
			end
		end
		redirect_to action: "edit", id: @match.id
	end

	def edit
		@match = Match.find(params[:id])
		@list_teams = Team.all.collect{|item| [item.name, item.id]}
		@games = @match.games
		@max_game_per_match = MAX_GAME_PER_MATCH
	end

	def update
		@match = Match.find(params[:id])
		update_is_invalid = MatchService.new.update_invalid?(params: params)
		if update_is_invalid
			flash[:err] = update_is_invalid
			redirect_to action: "edit", id: @match.id
			return
		end
		@match.team_a_id = params[:match][:team_a_id]
		@match.team_b_id = params[:match][:team_b_id]
		@match.save
		if params[:game].any?
			params[:game].each do |game|
				if !game[:winner].present? || !game[:score].present?
					next
				end
				if game[:id].present?
					current_game = Game.find(game[:id])
				else
					current_game = Game.new
				end
				current_game.match_id = @match.id
				current_game.winner_id = game[:winner]
				current_game.score = game[:score]
				current_game.save
			end
		end
		redirect_to action: "edit", id: @match.id
	end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	def index
		@teams = Team.all
	end

	def new
		@team = Team.new
	end

	def create
		@team = Team.new
		@team.name = params[:team][:name]
		@team.save
		redirect_to action: "edit", id: @team.id
	end

	def edit
		@team = Team.find(params[:id])
	end

	def update
		@team = Team.find(params[:id])
		@team.name = params[:team][:name]
		@team.save
		redirect_to action: "edit", id: @team.id
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custom_users_helper.rb
module CustomUsersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matchs_helper.rb
module MatchsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/common/_menu.html.erb
<div class="menu">
	<div>
		<%= link_to "Home", root_path %> | 
		<%= link_to "Users", custom_users_path %> | 
		<%= link_to "Teams", teams_path %> | 
		<%= link_to "Matchs", matchs_path %> | 
	<% if user_signed_in? %>
	  You are <%= current_user.first_name || "-" %> <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
	<% end %>
  </div>
</div>

app/views/custom_users/edit.html.erb
<%= render "common/menu" %>
<div>
	<%= form_for(@user, url: custom_user_path) do |form| %>
	<%= form.label :email %>
	<%= form.email_field :email %><br>
	<%= form.label :first_name %>
	<%= form.text_field :first_name %><br>
	<%= form.label :last_name %>
	<%= form.text_field :last_name %><br>
	<%= form.submit %>
	<% end %>
</div>

app/views/custom_users/index.html.erb
<%= render "common/menu" %>
<table>
<tr>
	<td>Email</td>
	<td>First name</td>
	<td>Last name</td>
	<td>Edit</td>
	<td>Delete</td>
</tr>
<% @users.each do |user| %>
<tr>
	<td><%= user.email %></td>
	<td><%= user.first_name || "-" %></td>
	<td><%= user.last_name || "-" %></td>
	<td><%= link_to "Edit", edit_custom_user_path(user.id) %></td>
	<td><%= link_to "Delete", custom_user_path(user.id), method: :delete, data: { confirm: "Are you sure you want to delete this users?" } %></td>
</tr>
<% end %>
</table>

app/views/home/index.html.erb
<%= render "common/menu" %>
<h1>Teams ranking:</h1>
<table>
		<tr>
			<td>Team name</td>
			<td>Match plays</td>
			<td>Win ratio</td>
		</tr>
	<% @teams.each do |team| %>
		<tr>
			<td><%= team["name"] %></td>
			<td><%= team["match_play"] %></td>
			<td><%= team["win_ratio"] %> %</td>
		</tr>
	<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A21Entry</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matchs/edit.html.erb
<%= render "common/menu" %>
<% if flash[:err] %>
	<ol>
	<% flash[:err].each do |err| %>
		<li><%= err %></li>
	<% end %>
	</ol>
<% end %>

<%= form_for(@match, url: match_path) do |form| %>
<%= form.label :team_a_id, "First team" %>
<%= form.select :team_a_id, @list_teams, :prompt => "Select" %><br>
<%= form.label :team_b_id, "Second team" %>
<%= form.select :team_b_id, @list_teams, :prompt => "Select" %><br>
<br>
<% @games.each_with_index do |game, index| %>
<%= label_tag "Game #{index + 1} result:" %><br>
<%= label_tag "Score:" %>
<%= text_field_tag "game[][score]", game.score %><br>
<%= label_tag "Winner:" %>
<%= select_tag "game[][winner]", options_for_select(@list_teams, game.winner_id), :prompt => "Select" %><br><br>
<%= hidden_field_tag "game[][id]", game.id %>
<% end %>
<% ((@games.count + 1)..@max_game_per_match).each do |game_no| %>
<%= label_tag "Game #{game_no} result:" %><br>
<%= label_tag "Score:" %>
<%= text_field_tag "game[][score]" %><br>
<%= label_tag "Winner:" %>
<%= select_tag "game[][winner]", options_for_select(@list_teams), :prompt => "Select" %><br><br>
<% end %>
<%= form.submit %>
<% end %>

app/views/matchs/index.html.erb
<%= render "common/menu" %>
<%= link_to "Create new match", new_match_path %>
<table>
<% @matchs.each do |match| %>
	<tr>
		<td><%= match.team_a.name %> VS <%= match.team_b.name %></td>
		<td><%= link_to "Edit", edit_match_path(match.id) %></td>
		<td><%= link_to "Delete", match_path(match.id), method: :delete, data: { confirm: "Are you sure you want to delete this match?" } %></td>
	</tr>
<% end %>
</table>

app/views/matchs/new.html.erb
<%= render "common/menu" %>
<% if flash[:err] %>
	<ol>
	<% flash[:err].each do |err| %>
		<li><%= err %></li>
	<% end %>
	</ol>
<% end %>

<%= form_for(@match, url: matchs_path) do |form| %>
<%= form.label :team_a_id, "First team" %>
<%= form.select :team_a_id, @list_teams, :prompt => "Select" %><br>
<%= form.label :team_b_id, "Second team" %>
<%= form.select :team_b_id, @list_teams, :prompt => "Select" %><br>
<br>
<% (1..3).each do |game_no| %>
<%= label_tag "Game #{game_no} result:" %><br>
<%= label_tag "Score:" %>
<%= text_field_tag "game[][score]" %><br>
<%= label_tag "Winner:" %>
<%= select_tag "game[][winner]", options_for_select(@list_teams), :prompt => "Select" %><br><br>
<% end %>
<%= form.submit %>
<% end %>